name = "MCPRepl"
uuid = "b62cb57a-788d-40b5-9d64-84a1dfc37ce3"
authors = ["Hans WÃ¼rfel <git@wuerfel.io>"]
version = "0.1.0"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
Dates = "1.10"
JSON3 = "1.14.3"
REPL = "1.10"
Sockets = "1.10"
Test = "1.10"

[extras]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Dates"]
